"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { isSupabaseConfigured, supabase } from "@/lib/supabase";
import type { TrialCase } from "@/types";
const demo: TrialCase[] = [{ id: "demo", slug: "demo", name: "小王", title: "一级拖延重犯", avatar_url: null, punishment: "请大家喝奶茶", heat_count: 10 }];
export default function CaseForum() {
  const [cases, setCases] = useState<TrialCase[]>(demo); const [ready, setReady] = useState(false); const [name, setName] = useState(""); const [title, setTitle] = useState(""); const [avatarFile, setAvatarFile] = useState<File | null>(null); const [submitting, setSubmitting] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { if (!supabase) return; const client = supabase; let active = true; client.from("cases").select("*").order("created_at", { ascending: false }).then(({ data }) => { if (active && data) setCases(data); setReady(true); }); const channel = client.channel("case-forum").on("postgres_changes", { event: "INSERT", schema: "public", table: "cases" }, (p) => setCases((old) => [p.new as TrialCase, ...old])).on("postgres_changes", { event: "UPDATE", schema: "public", table: "cases" }, (p) => setCases((old) => old.map((item) => item.id === p.new.id ? p.new as TrialCase : item))).subscribe(); return () => { active = false; client.removeChannel(channel); }; }, []);
  const createCase = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!supabase) { setMessage("请先配置 Supabase"); return; } if (avatarFile && (!avatarFile.type.startsWith("image/") || avatarFile.size > 2 * 1024 * 1024)) { setMessage("请选择 2MB 以内的图片文件"); return; } setSubmitting(true); let avatarUrl: string | null = null; if (avatarFile) { const extension = avatarFile.name.split(".").pop() || "jpg"; const path = `${crypto.randomUUID()}.${extension}`; const { error: uploadError } = await supabase.storage.from("avatars").upload(path, avatarFile, { contentType: avatarFile.type }); if (uploadError) { setSubmitting(false); setMessage("头像上传失败，请重试"); return; } avatarUrl = supabase.storage.from("avatars").getPublicUrl(path).data.publicUrl; } const slug = `case-${crypto.randomUUID().slice(0, 8)}`; const { data, error } = await supabase.from("cases").insert({ slug, name: name.trim(), title: title.trim(), avatar_url: avatarUrl, punishment: "请大家喝奶茶" }).select().single(); setSubmitting(false); if (error) { setMessage("创建失败，请重试"); return; } window.location.href = `/case/${data.slug}`; };
  return <main><div className="noise" /><section className="shell forum"><header className="topline"><span>PUBLIC TRIAL</span><span>案件广场</span></header><div className="forum-hero"><h1>公开案件广场</h1><p>每个案件都有独立罪状、热度与群众判决。</p></div><form className="crime-form new-case" onSubmit={createCase}><h2>＋ 提交新的被讨伐对象</h2><p>仅限轻松玩笑；不要使用真实严重指控、隐私或未经允许的照片。</p><input required maxLength={24} value={name} onChange={(e) => setName(e.target.value)} placeholder="对方昵称，例如：小陈" /><input required maxLength={36} value={title} onChange={(e) => setTitle(e.target.value)} placeholder="搞笑称号，例如：消息已读消失术大师" /><label className="upload-label">头像图片（可选，2MB 以内）<input type="file" accept="image/*" onChange={(e) => setAvatarFile(e.target.files?.[0] ?? null)} /></label><button type="submit" disabled={submitting}>{submitting ? "正在立案…" : "提交案件"}</button>{message && <p>{message}</p>}</form><div className="section-heading"><span>正在审理</span><small>{ready ? `${cases.length} 个案件` : "读取中…"}</small></div><div className="case-grid">{cases.map((item) => <Link className="case-card" href={`/case/${item.slug}`} key={item.id}><div className="case-avatar">{item.avatar_url ? <img src={item.avatar_url} alt="" /> : "😈"}</div><div><small>CASE #{item.id === "demo" ? "000001" : item.id.slice(0, 6).toUpperCase()}</small><h2>{item.name}</h2><p>{item.title}</p><b>🔥 {item.heat_count.toLocaleString()}</b></div></Link>)}</div></section></main>;
}
